spring:
  profiles:
    active: ${SPRING_AMB}

  application:
    name: api-gateway

  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enable: true
          #lower-case-server-id: true

  server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#management:
 # endpoint:
  #  health:
   #   show-details: always
  #endpoints:
  #  web:
   #   exposure:
   #     include: gateway, health, info
  #info:
   # build:
    #  enabled: true
    #env:
    #  enabled: true

#info:
 # app:
  #  name: @project.name@
   # description: @project.description@
    #version: @project.version@
    #encoding: @project.build.sourceEncoding@
    #java.version: @java.version@