spring:
  profiles:
    active: ${SPRING_AMB}

  application:
    name: api-financeiro

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baselineOnMigrate: true

  security:
    token:
      secret: ${JWT_SECURITY:my-security-key}

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}