spring:
  profiles:
    active: ${SPRING_AMB}

  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    defaultZone: http://discovery-server:8761/eureka/
 