spring:
  jpa:
    database: POSTGRESQL
    show-sql: false

  datasource:
    url: jdbc:postgresql://172.16.238.10:5432/banco-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: 172.16.238.11
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  error:
    include-stacktrace: never
