spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://192.168.15.15:5432/banco-service
    #url: jdbc:postgresql://172.16.238.10:5432/banco-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://192.168.15.15:8761/eureka

server:
  error:
    include-stacktrace: always

