spring:
  profiles:
    active: ${SPRING_AMB}

  application:
    name: banco-service

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baselineOnMigrate: true

  security:
    token:
      secret: ${JWT_SECURITY:my-security-key}

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

