spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    #platform: postgres
    url: jdbc:postgresql://192.168.15.15:5432/banco-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  error:
    include-stacktrace: always
