spring:
  jpa:
    database: POSTGRESQL
    show-sql: false

  datasource:
    url: jdbc:postgresql://172.16.238.10:5432/banco-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  rabbitmq:
    host: 172.16.238.12
    port: 5672
    username: admin
    password: admin

server:
  error:
    include-stacktrace: never